name: published_gen
description: A new Flutter package.
version: 0.0.10
homepage: https://github.com/harisk92/dart_published

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  build: ^2.0.1
  build_config: ^1.0.0
  source_gen: ^1.0.0
  published: ">=0.0.10 <1.0.0"
  analyzer: ^2.3.0


dev_dependencies:
  json_serializable: ^5.0.0
  json_annotation: ^4.1.0
  build_test: ^2.1.0
  build_runner: ^2.0.0
  test: ^1.16.8
  matcher: ^0.12.10
  source_gen_test: ^1.0.1




